# Generated by Django 3.2.9 on 2021-11-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=5)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('nodes_used', models.CharField(max_length=6)),
            ],
        ),
    ]
